name: Hello World

on: [push]

jobs:
    hola:
        runs-on: ubuntu-latest

        steps:
        - name: Hello World!
          run: echo "Hello World!"

    other:
        runs-on: macos-12

        steps:
        - name: LS!
          run: ls -lr